apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-knative
  annotations:
    features.knative.dev/podspec-runtimeclassname: "enabled"
    io.containerd.cri.runtime-handler: kata-qemu-sev
spec:
  template:
    metadata:
      labels:
        apps.coco-serverless/name: helloworld-py
        io.katacontainers.config.pre_attestation.enabled: "false"
    spec:
      runtimeClassName: kata-qemu-sev
      # coco-knative: need to run user container as root
      securityContext:
        runAsUser: 1000
      containers:
        - image: external-registry.coco-csg.com/tf-app:unencrypted-nydus #external-registry.coco-csg.com/helloworld-py:unencrypted #konsougiou/alpine-sev-tests:flask #ghcr.io/csegarragonz/coco-helloworld-py:unencrypted
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
