apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-knative
spec:
  template:
    spec:
      containers:
        # TODO: change for csegarragonz/coco-helloworld-py:latest
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
