apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-knative
    #   annotations:
    #     "features.knative.dev/podspec-volumes-emptydir": "enabled"
    #     "features.knative.dev/podspec-persistent-volume-claim": "enabled"
    #     "features.knative.dev/podspec-persistent-volume-claim-write": "enabled"
    #     "features.knative.dev/podspec-runtimeclassname": "enabled"
spec:
  # ConfigurationSpec (or RevisionTemplateSpec?)
  template:
    metadata:
      labels:
        apps.coco-serverless/name: helloworld-py
          # io.katacontainers.config.pre_attestation.enabled: "false"
    spec:
      runtimeClassName: kata-qemu
      containers:
        - image: csegarragonz/coco-helloworld-py:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
          securityContext:
            capabilities:
              add:
                - CAP_SYS_ADMIN
