apiVersion:  v1
kind:  ConfigMap
metadata:
  name:  config-features
  namespace:  knative-serving
data:
  kubernetes.podspec-runtimeclassname: "enabled"
  kubernetes.podspec-securitycontext: "enabled"
  registriesSkippingTagResolving: registry.csg-coco.com
