apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: knative-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.240-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: knative-l2-ip-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - knative-ip-pool
