apiVersion: v1
kind: Service
metadata:
  name: coco-fio-benchmark-node-port
spec:
  type: NodePort
  selector:
    apps.coco-serverless/name: fio-benchmark
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
