apiVersion: batch/v1
kind: Job
metadata:
  name: coco-helloworld-nydus
  labels:
    apps.coco-serverless/name: helloworld-py
  annotations: 
    io.containerd.cri.runtime-handler: kata-qemu-sev

    spec:
      restartPolicy: Never
      runtimeClassName: kata-qemu-sev
      containers:
      - name: helloworld-py
        image: external-registry.coco-csg.com/tf-serving:unencrypted #konsougiou/tf-app:unencrypted  #external-registry.coco-csg.com/fio-benchmark:unencrypted  #localhost:5000/hello-world-flask-nydus:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      #   volumeMounts:  
      #   - name: ca-certstore
      #     mountPath: /home/ksougioultzoglou/FYP/coco-serverless-fyp/.config/local-registry/domain.crt
      #   env:
      #   - name: SSL_CERT_DIR
      #     value: /home/ksougioultzoglou/FYP/coco-serverless-fyp/.config/local-registry/domain.crt
      # volumes:  
      # - name: ca-certstore
      #   configMap:
      #     name: ca-certstore
