apiVersion: v1
kind: Service
metadata:
  name: coco-helloworld-py-node-port
spec:
  type: NodePort
  selector:
    apps.sc2.io/name: helloworld-py
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coco-helloworld-py
  labels:
    apps.sc2.io/name: helloworld-py
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.sc2.io/name: helloworld-py
  template:
    metadata:
      labels:
        apps.sc2.io/name: helloworld-py
    spec:
      runtimeClassName: kata-${SC2_RUNTIME_CLASS}
      containers:
      - name: helloworld-py
        image: sc2cr.io/applications/helloworld-py:unencrypted
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
