apiVersion: v1
kind: Service
metadata:
  name: coco-helloworld-py-node-port
spec:
  type: NodePort
  selector:
    apps.sc2.io/name: helloworld-py
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
