apiVersion: apps/v1
kind: Deployment
metadata:
  name: coco-helloworld-py
  labels:
    apps.coco-serverless/name: helloworld-py
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.coco-serverless/name: helloworld-py
  template:
    metadata:
      labels:
        apps.coco-serverless/name: helloworld-py
        io.katacontainers.config.pre_attestation.enabled: "false"
    spec:
      runtimeClassName: kata-qemu-sev
      containers:
      - name: helloworld-py
        image: registry.coco-csg.com/csegarragonz/coco-helloworld-py:encrypted
        # image: ghcr.io/csegarragonz/coco-helloworld-py:encrypted
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
