apiVersion: apps/v1
kind: Deployment
metadata:
  name: coco-helloworld-py
  labels:
    apps.coco-serverless/name: helloworld-py
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.coco-serverless/name: helloworld-py
  template:
    metadata:
      labels:
        apps.coco-serverless/name: helloworld-py
        io.katacontainers.config.pre_attestation.enabled: "false"
    spec:
      runtimeClassName: kata-qemu
      containers:
      - name: helloworld-py
        # image: csegarragonz/coco-helloworld-py:latest
        image: csegarragonz/coco-helloworld-py@sha256:af0fec55e9aed9a259e8da9dcaa28ab3fc1277dc8db4b8883265f98272cef11d
          # imagePullPolicy: Always
        ports:
        - containerPort: 8080
