apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-knative
spec:
  template:
    metadata:
      labels:
        apps.sc2.io/name: helloworld-py
    spec:
      runtimeClassName: kata-qemu-snp
      # coco-knative: need to run user container as root
      securityContext:
        runAsUser: 1000
      containers:
        - image: sc2cr.io/applications/helloworld-py:unencrypted
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World"
